if isunix
    % Linux or macOS
   eigen_dir = '/usr/include/eigen3';

   mex(['-I' eigen_dir], ...
    'CXXFLAGS=$CXXFLAGS -std=c++17', ...
    'CXXOPTIMFLAGS=$CXXOPTIMFLAGS -O3 -DNDEBUG', ...
    'solver_depth_3ac_core.cpp');

   mex(['-I' eigen_dir], ...
    'CXXFLAGS=$CXXFLAGS -std=c++17', ...
    'CXXOPTIMFLAGS=$CXXOPTIMFLAGS -O3 -DNDEBUG', ...
    'det2x2poly.cpp');

   mex(['-I' eigen_dir], ...
    'CXXFLAGS=$CXXFLAGS -std=c++17', ...
    'CXXOPTIMFLAGS=$CXXOPTIMFLAGS -O3 -DNDEBUG', ...
    'det4x4poly.cpp');
elseif ispc
    % Windows
    eigen_dir = 'D:/eigen-3.4.0';

    mex(['-I' eigen_dir], ...
    'COMPFLAGS=$COMPFLAGS /std:c++17', ...
    'CXXOPTIMFLAGS=$CXXOPTIMFLAGS /O2 /DNDEBUG', ...
    'solver_depth_3ac_core.cpp');
    
    mex(['-I' eigen_dir], ...
    'COMPFLAGS=$COMPFLAGS /std:c++17', ...
    'CXXOPTIMFLAGS=$CXXOPTIMFLAGS /O2 /DNDEBUG', ...
    'det2x2poly.cpp');

    mex(['-I' eigen_dir], ...
    'COMPFLAGS=$COMPFLAGS /std:c++17', ...
    'CXXOPTIMFLAGS=$CXXOPTIMFLAGS /O2 /DNDEBUG', ...
    'det4x4poly.cpp');
else
    disp('Unknown operating system');
end

